# Model stuff
MODEL_NAME: 3DAmodalFormer
MODEL_CLASS: model:3DAmodalFormer
MODEL:
    WEIGHTS: "../checkpoints/"
    BACKBONE: "fasterrcnn_resnet50_fpn" #hardcoded for now
    PARAMS:
        INPUT_H: 250 # 540
        INPUT_W: 828 # 960
        IN_CHANS : 3
        ROI_OUT_SIZE: 16
        Q_DIM: 3
        EMBED_DIM : 256
        NUM_HEADS: 1
        NUM_LAYERS: 1
        NUM_OUTPUT_MASKS: 4
    PATH: /home/jule-magnus/dd2414/merge_repo/3damodal/3DAmodal/model_checkpoints/pretrained_pointpillars_epoch_160.pth
# Training params
OPTIMIZER: SGD # Hard coded rn
OPTIMIZER_MOMENTUM:
    BETA1: 0.9
    BETA2: 0.95
WEIGHT_DECAY: 5.0e-2 
BASE_LEARNING_RATE: 1.0e-3
LEARNING_RATE: 0.05
MIN_LEARNING_RATE: 0.0
LEARNING_RATE_SCHEDULER: cosine decay # Hard coded rn
EPOCHS: 2000
CHECK_VAL_EVERY_N_EPOCH: 1
RANDOM_SEED: 42
DATASET: 
    NAME: datasets.KINS_dataset:KINS # datasets.asd_dataset:AmodalSynthDriveDataset
    TRAIN: /home/jule-magnus/dd2414/Data/ #/local_storage/users/tibbe/datasets/KINS/ # /local_storage/users/tibbe/datasets/AmodalSynthDrive/train/ 
    # /Midgard/Data/tibbe/datasets/AmodalSynthDrive/train
    TEST: /home/jule-magnus/dd2414/Data/ #/local_storage/users/tibbe/datasets/AmodalSynthDrive/test/
BATCH_SIZE: 1
OUTPUT_DIR:
    TRAINING: "./outputs/training/"
    TESTING: "./outputs/testing/"
DEVICE: 'cuda'
DISTRIBUTED:
    MODEL: False
    DATA: True
SAVE_INTERVAL: 20
START_FROM_CKPT: True
CKPT_PATH: /home/jule-magnus/dd2414/merge_repo/3damodal/3DAmodal/checkpoints_orig/aisformer_r50_kins.pth #"/Midgard/home/tibbe/3damodal/3DAmodal/checkpoint_orig/aisformer_r50_kins.pth"
SAVE_CKPT_FOLDER: /home/jule-magnus/dd2414/merge_repo/3damodal/3DAmodal/checkpoints #"/Midgard/home/tibbe/3damodal/3DAmodal/checkpoints"
RUNS_FOLDER: /home/jule-magnus/dd2414/merge_repo/3damodal/3DAmodal/runs #"/Midgard/home/tibbe/3damodal/3DAmodal/runs"
LOG_LEVEL: INFO