# Model stuff
MODEL_NAME: 3DAmodalFormer
MODEL_CLASS: model:3DAmodalFormer
MODEL:
    WEIGHTS: "../checkpoints/"
    BACKBONE: "fasterrcnn_resnet50_fpn" #hardcoded for now
    PARAMS:
        INPUT_H: 540
        INPUT_W: 960
        IN_CHANS : 3
        ROI_OUT_SIZE: 32
        PATCH_SIZE: 16
        Q_DIM: 3
        EMBED_DIM : 3
        ENCODER_DEPTH : 24
        ENCODER_HIDDEN_DIM : 1
        ENCODER_NUM_HEADS : 3
        DECODER_EMBED_DIM : 3
        DECODER_DEPTH : 8
        DECODER_HIDDEN_DIM : 1
        DECODER_NUM_HEADS : 3


# Training params
OPTIMIZER: SGD # Hard coded in src/pretraining.py
OPTIMIZER_MOMENTUM:
    BETA1: 0.9
    BETA2: 0.95
WEIGHT_DECAY: 5.0e-2 
BASE_LEARNING_RATE: 1.0e-3
LEARNING_RATE: 2.5e-3
MIN_LEARNING_RATE: 0.0
LEARNING_RATE_SCHEDULER: cosine decay # Hard coded in src/pretraining.py
WARMUP_EPOCHS: 40
EPOCHS: 2000 
EPOCHS_ABLATION: 400
CHECK_VAL_EVERY_N_EPOCH: 1
ABLATION: False 
MASK_RATIO: 0.95
RANDOM_SEED: 42
DATASET: 
    NAME: datasets.KINS_dataset:KINS # datasets.asd_dataset:AmodalSynthDriveDataset
    TRAIN: /Midgard/Data/tibbe/datasets/KINS/ #/Midgard/Data/tibbe/datasets/AmodalSynthDrive/train
    #/local_storage/users/tibbe/datasets/AmodalSynthDrive/train/
    TEST: /local_storage/users/tibbe/datasets/AmodalSynthDrive/test/
AUGMENTATION:   # Proably hard coded
    - hflip
    - crop:
        - 0.5
        - 1
BATCH_SIZE: 1
OUTPUT_DIR:
    TRAINING: "./outputs/training/"
    TESTING: "./outputs/testing/"